In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import kagglehub

from sklearn.preprocessing import LabelEncoder

In [3]:
# Download latest version
path = kagglehub.dataset_download("aravinii/house-price-prediction-treated-dataset")

df = pd.read_csv(path+'/df_train.csv')

In [4]:
df

date     price  bedrooms  grade  has_basement  living_in_m2  \
0      2014-05-15  312000.0         2      2          True     138.42547   
1      2014-11-14  310000.0         2      2         False     105.90942   
2      2014-12-24  320000.0         2      2         False     117.98681   
3      2015-02-22  264500.0         2      3         False     151.43189   
4      2015-01-06  700000.0         3      2          True     341.88304   
...           ...       ...       ...    ...           ...           ...   
13598  2014-10-07  353950.0         3      3         False     302.86378   
13599  2014-08-08  289950.0         2      2         False     155.14801   
13600  2014-07-17  625504.0         2      3          True     117.98681   
13601  2014-11-26  730000.0         3      5         False     340.02498   
13602  2014-08-12  383000.0         3      3         False     220.18011   

       renovated  nice_view  perfect_condition  real_bathrooms  has_lavatory  \
0          False      False              False               2          True   
1          False      False              False               1          True   
2          False       True              False               1         False   
3          False      False              False               2          True   
4          False      False              False               3         False   
...          ...        ...                ...             ...           ...   
13598      False      False              False               2          True   
13599      False      False              False               2          True   
13600      False      False              False               2          True   
13601      False      False              False               2          True   
13602      False      False              False               2          True   

       single_floor  month  quartile_zone  
0             False      5              1  
1             False     11              3  
2              True     12              2  
3              True      2              1  
4             False      1              4  
...             ...    ...            ...  
13598         False     10              1  
13599         False      8              2  
13600         False      7              4  
13601         False     11              4  
13602         False      8              1  

[13603 rows x 14 columns]

In [13]:
#Defining the dataset

# Initialize LabelEncoder
label_encoder = LabelEncoder()

df['has_basement'] = label_encoder.fit_transform(df['has_basement'])
df['renovated'] = label_encoder.fit_transform(df['renovated'])
df['nice_view'] = label_encoder.fit_transform(df['nice_view'])
df['perfect_condition'] = label_encoder.fit_transform(df['perfect_condition'])
df['has_lavatory'] = label_encoder.fit_transform(df['has_lavatory'])
df['single_floor'] = label_encoder.fit_transform(df['single_floor'])

Y_df = df['price']

In [15]:
print(Y_df)

0        312000.0
1        310000.0
2        320000.0
3        264500.0
4        700000.0
           ...   
13598    353950.0
13599    289950.0
13600    625504.0
13601    730000.0
13602    383000.0
Name: price, Length: 13603, dtype: float64


In [16]:
#Convert to numpy array

X_data_array = df.to_numpy()
Y_data_array = Y_df.to_numpy()
print(Y_data_array)

[312000. 310000. 320000. ... 625504. 730000. 383000.]


In [17]:
#Test Train split

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_data_array,Y_data_array,test_size=0.05)


m = X_train.shape


In [19]:
print(X_train.shape)
print(Y_train.shape)


(12922, 13)
(12922,)


In [21]:
print(X_test.shape)
print(Y_test.shape)

(681, 13)
(681,)


In [651]:
#Defining weights and bias 
# Y = WX  +  B
'''
W = np.random.rand(1, 1)
B = np.random.rand(1, 1)

print("W size :",W.shape)
print("B size :",B.shape)
print("X train size :",X_train.shape)
print("X test size :",X_test.shape)
print("W mat",W)
print("B mat",B)
'''

# Y is an array of size (M,1) , X = (M,N) here N = 1, hence W = (1,1), B = (M,1)

'\nW = np.random.rand(1, 1)\nB = np.random.rand(1, 1)\n\nprint("W size :",W.shape)\nprint("B size :",B.shape)\nprint("X train size :",X_train.shape)\nprint("X test size :",X_test.shape)\nprint("W mat",W)\nprint("B mat",B)\n'

In [764]:
#Defining the learning rate

learning_rate = 0.0001


In [37]:
# Implementing the linear regression Fully 
#Defining weights and bias 
# Y = WX  +  B
import random 

W = np.array([0]*13)
B = np.array(0)


#W = 9992.95668876
#B = -16632126.19550556

print("Initial W and B : ", W, B)

#Defining the learning rate

learning_rate = 0.0000001

#Defining the number of epochs
epochs = 100000
W_list = []
B_list = []
error_tracker = []

m = X_train.shape[0]

for e in range(epochs):
    #forward pass
    y = np.add(np.multiply(W,X_train),B)
    
        
#Testing the model with test data

predicted_Y = []
for (i,x) in enumerate(X_train):
    y = W * x + B
    predicted_Y.append(y)

Initial W and B :  [0 0 0 0 0 0 0 0 0 0 0 0 0] 0
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12922, 13)
(12

In [24]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
X_train = X_train.reshape(-1,13)
Y_train = Y_train.reshape(-1,1)
lin_reg.fit(X_train,Y_train)

LinearRegression()

In [26]:
y_predict = lin_reg.predict(X_test.reshape(-1,13))
y_train_predict = lin_reg.predict(X_train)
print(lin_reg.coef_,lin_reg.intercept_)

[[ 1.00000000e+00  1.24593858e-11 -1.71672173e-12 -2.56099295e-11
  -2.98653206e-13 -6.83213766e-12  6.79011291e-12 -1.07089076e-11
   2.86382407e-12  3.58993057e-11  2.96015351e-11 -3.71066686e-12
   2.19447280e-11]] [2.56113708e-09]


In [28]:
y_train_predict[0]

array([463800.])

In [29]:
Y_train[0]

array([463800.])